# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

resources:
  repositories:
    - repository: python-sample-vscode-flask-tutorial
      type: github
      name: mingmingkong-gd/python-sample-vscode-flask-tutorial
      endpoint: mingmingkong-gd
    # - repository: kmmtestrepo
    #   type: github
    #   name: kmmtestrepo
    #   endpoint: ado-test

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    trigger_branch: master
  ${{ if eq(variables['Build.SourceBranchName'], 'release') }}: 
    trigger_branch: release



trigger:
- master






pool: Default


jobs:
- job: testb
  steps:
  - checkout: self
  # - checkout: kmmtestrepo
  - template: template.yml
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here       
        echo "the  Build.BuildNumber is $(Build.BuildNumber)"
        echo " current workspace is $(Agent.BuildDirectory)"
        echo "current dir is  $(Build.SourcesDirectory)"
        echo "source branch is $(Build.SourceBranch)"
        echo "trigger branch is $(trigger_branch)"
        echo testabc



