# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

resources:
  repositories:
    - repository: python-sample-vscode-flask-tutorial
      type: github
      name: mingmingkong-gd/python-sample-vscode-flask-tutorial
      endpoint: mingmingkong-gd
    - repository: kmmtestrepo-a
      type: github
      name: mingmingkong-gd/kmmtestrepo
      endpoint: mingmingkong-gd
    

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    trigger_branch: master
  ${{ if eq(variables['Build.SourceBranchName'], 'release') }}: 
    trigger_branch: release



trigger:
- master






pool: Default


jobs:
- job: testb
  steps:
  - checkout: self
  - checkout: kmmtestrepo-a
  - template: template.yml
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here       
        echo "the  Build.BuildNumber is $(Build.BuildNumber)"
        echo " current workspace is $(Agent.BuildDirectory)"
        echo "current dir is  $(Build.SourcesDirectory)"
        echo "source branch is $(Build.SourceBranch)"
        echo "trigger branch is $(trigger_branch)"
        echo "default working directory $(System.DefaultWorkingDirectory)"
        echo "build repo name $(Build.Repository.Name)" 
        echo "build source version $(Build.SourceVersion)"
        echo " pipeline workspace $(Pipeline.Workspace)"




